CREATE TABLE "audit_logs_hipaa" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"session_id" text,
	"ip_address" text,
	"user_agent" text,
	"action" text NOT NULL,
	"resource_type" text NOT NULL,
	"resource_id" integer,
	"fields_accessed" jsonb,
	"phi_fields_count" integer DEFAULT 0,
	"request_method" text,
	"request_path" text,
	"request_body" text,
	"response_status" integer,
	"response_time" integer,
	"security_level" text DEFAULT 'standard',
	"risk_score" integer DEFAULT 0,
	"hipaa_compliant" boolean DEFAULT true,
	"data_retention_date" timestamp,
	"correlation_id" text,
	"trace_id" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "clients_hipaa" (
	"id" serial PRIMARY KEY NOT NULL,
	"therapist_id" integer NOT NULL,
	"name" text NOT NULL,
	"email_encrypted" text,
	"phone_encrypted" text,
	"address_encrypted" text,
	"city_encrypted" text,
	"state_encrypted" text,
	"zip_code_encrypted" text,
	"date_of_birth_encrypted" text,
	"gender_encrypted" text,
	"race_encrypted" text,
	"ethnicity_encrypted" text,
	"pronouns_encrypted" text,
	"hometown_encrypted" text,
	"notes_encrypted" text,
	"diagnosis_codes_encrypted" text,
	"treatment_history_encrypted" text,
	"primary_diagnosis_code_encrypted" text,
	"secondary_diagnosis_code_encrypted" text,
	"referring_physician_encrypted" text,
	"referring_physician_npi_encrypted" text,
	"insurance_info_encrypted" text,
	"authorization_info_encrypted" text,
	"prior_auth_number_encrypted" text,
	"member_id_encrypted" text,
	"group_number_encrypted" text,
	"primary_insured_name_encrypted" text,
	"email_search_hash" text,
	"phone_search_hash" text,
	"status" text DEFAULT 'active',
	"type" text DEFAULT 'individual',
	"billing_type" text DEFAULT 'private_pay',
	"session_cost" numeric(10, 2),
	"no_show_fee" numeric(10, 2),
	"default_cpt_code" text,
	"place_of_service" text DEFAULT '11',
	"authorization_required" boolean DEFAULT false,
	"copay_amount" numeric(10, 2),
	"deductible_amount" numeric(10, 2),
	"photo_filename" text,
	"photo_original_name" text,
	"photo_mime_type" text,
	"stripe_customer_id" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"deleted" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "sessions_hipaa" (
	"id" serial PRIMARY KEY NOT NULL,
	"therapist_id" integer NOT NULL,
	"client_id" integer NOT NULL,
	"date" timestamp NOT NULL,
	"duration" integer DEFAULT 50,
	"type" text DEFAULT 'individual',
	"status" text DEFAULT 'scheduled',
	"notes_encrypted" text,
	"assessments_encrypted" text,
	"treatment_goals_encrypted" text,
	"progress_notes_encrypted" text,
	"cpt_code" text,
	"add_on_cpt_codes" jsonb DEFAULT '[]'::jsonb,
	"authorization_required" boolean DEFAULT false,
	"authorization_number" text,
	"is_paid" boolean DEFAULT false,
	"payment_id" text,
	"is_intake" boolean DEFAULT false,
	"session_format" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "therapist_phi" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"ssn_encrypted" text,
	"date_of_birth_encrypted" text,
	"personal_address_encrypted" text,
	"personal_phone_encrypted" text,
	"personal_email_encrypted" text,
	"birth_city_encrypted" text,
	"birth_state_encrypted" text,
	"birth_country_encrypted" text,
	"is_us_citizen" boolean,
	"work_permit_visa_encrypted" text,
	"emergency_contact_encrypted" text,
	"emergency_phone_encrypted" text,
	"personal_email_search_hash" text,
	"personal_phone_search_hash" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "therapist_profiles" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"title" text,
	"license_number" text,
	"license_state" varchar(2),
	"license_expiration_date" timestamp,
	"specialties" jsonb DEFAULT '[]'::jsonb,
	"languages" jsonb DEFAULT '[]'::jsonb,
	"session_format" text,
	"base_rate" numeric(10, 2),
	"sliding_scale" boolean DEFAULT false,
	"therapist_identities" jsonb DEFAULT '[]'::jsonb,
	"business_address" text,
	"business_city" varchar(100),
	"business_state" varchar(50),
	"business_zip_code" varchar(10),
	"business_phone" text,
	"business_email" text,
	"npi_number" varchar(20),
	"taxonomy_code" varchar(20),
	"ein_number" varchar(20),
	"legal_business_name" varchar(255),
	"default_note_format" text DEFAULT 'SOAP',
	"session_duration" integer DEFAULT 50,
	"time_zone" text DEFAULT 'America/New_York',
	"is_insurance_provider" boolean DEFAULT false,
	"accepted_providers" jsonb DEFAULT '[]'::jsonb,
	"group_session_rate" numeric(10, 2),
	"cv_filename" text,
	"cv_original_name" text,
	"cv_mime_type" text,
	"cv_parsed_for_credentialing" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "treatment_plans_hipaa" (
	"id" serial PRIMARY KEY NOT NULL,
	"therapist_id" integer NOT NULL,
	"client_id" integer NOT NULL,
	"version" integer NOT NULL,
	"status" text DEFAULT 'active',
	"content_encrypted" text,
	"goals_encrypted" text,
	"objectives_encrypted" text,
	"interventions_encrypted" text,
	"progress_notes_encrypted" text,
	"start_date" timestamp,
	"end_date" timestamp,
	"review_date" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "users_auth" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	"email" text NOT NULL,
	"account_status" text DEFAULT 'active',
	"mfa_enabled" boolean DEFAULT false,
	"last_login" timestamp,
	"failed_login_attempts" integer DEFAULT 0,
	"account_locked_until" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_auth_username_unique" UNIQUE("username")
);
--> statement-breakpoint
ALTER TABLE "audit_logs_hipaa" ADD CONSTRAINT "audit_logs_hipaa_user_id_users_auth_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users_auth"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clients_hipaa" ADD CONSTRAINT "clients_hipaa_therapist_id_users_auth_id_fk" FOREIGN KEY ("therapist_id") REFERENCES "public"."users_auth"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions_hipaa" ADD CONSTRAINT "sessions_hipaa_therapist_id_users_auth_id_fk" FOREIGN KEY ("therapist_id") REFERENCES "public"."users_auth"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions_hipaa" ADD CONSTRAINT "sessions_hipaa_client_id_clients_hipaa_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients_hipaa"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "therapist_phi" ADD CONSTRAINT "therapist_phi_user_id_users_auth_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users_auth"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "therapist_profiles" ADD CONSTRAINT "therapist_profiles_user_id_users_auth_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users_auth"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "treatment_plans_hipaa" ADD CONSTRAINT "treatment_plans_hipaa_therapist_id_users_auth_id_fk" FOREIGN KEY ("therapist_id") REFERENCES "public"."users_auth"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "treatment_plans_hipaa" ADD CONSTRAINT "treatment_plans_hipaa_client_id_clients_hipaa_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients_hipaa"("id") ON DELETE cascade ON UPDATE no action;