#!/bin/bash

# Production AI Error Diagnostic and Fix Script
# Addresses the "I'm sorry, I encountered an error" issue

echo "🔧 Production AI Error Diagnostic & Fix"
echo "======================================="
echo ""

echo "📋 Issue Identified:"
echo "   Error: 'I'm sorry, I encountered an error. Please try again.'"
echo "   Source: Client-side error handling in SigieAssistant.tsx"
echo "   Cause: API call to /api/sigie is failing"
echo ""

echo "🔍 Most Likely Causes:"
echo "   1. OpenAI API key invalid/expired"
echo "   2. OpenAI API rate limit exceeded"
echo "   3. OpenAI service outage"
echo "   4. Authentication session expired"
echo "   5. Server-side error in sigie route"
echo ""

echo "🛠️  Step-by-Step Fix:"
echo "====================="
echo ""

echo "STEP 1: Check Render Environment Variables"
echo "------------------------------------------"
echo "1. Go to https://dashboard.render.com"
echo "2. Find your 'loma-platform' service"
echo "3. Go to Environment tab"
echo "4. Verify these keys are set and valid:"
echo "   - OPENAI_API_KEY (should start with 'sk-' and be 51 chars)"
echo "   - ANTHROPIC_API_KEY (should start with 'sk-ant-' and be 39 chars)"
echo "   - HUGGINGFACE_API_KEY (should start with 'hf_' and be 37 chars)"
echo ""

echo "STEP 2: Check Render Service Logs"
echo "--------------------------------"
echo "1. In Render dashboard, go to Logs tab"
echo "2. Try sending 'hello' in Clinical Admin chat"
echo "3. Look for these error patterns:"
echo "   - 'OPENAI_API_KEY not set'"
echo "   - 'OpenAI API Error'"
echo "   - 'AI service temporarily unavailable'"
echo "   - 'Failed to process request'"
echo ""

echo "STEP 3: Test API Keys Manually"
echo "------------------------------"
echo "If you have access to your API keys, test them:"
echo ""
echo "# Test OpenAI API key"
echo "curl -H 'Authorization: Bearer YOUR_OPENAI_KEY' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"model\": \"gpt-3.5-turbo\", \"messages\": [{\"role\": \"user\", \"content\": \"hello\"}]}' \\"
echo "     https://api.openai.com/v1/chat/completions"
echo ""

echo "STEP 4: Common Fixes"
echo "-------------------"
echo ""
echo "🔑 If API key is missing/invalid:"
echo "   1. Update in Render dashboard"
echo "   2. Redeploy service"
echo ""
echo "⏱️  If rate limit exceeded:"
echo "   1. Wait 1 hour"
echo "   2. Check OpenAI usage dashboard"
echo "   3. Consider upgrading OpenAI plan"
echo ""
echo "🔄 If service outage:"
echo "   1. Check https://status.openai.com"
echo "   2. Wait for service restoration"
echo "   3. Consider fallback to Anthropic API"
echo ""

echo "STEP 5: Alternative Solutions"
echo "-----------------------------"
echo ""
echo "🔄 Switch to Anthropic (if OpenAI fails):"
echo "   1. Ensure ANTHROPIC_API_KEY is set in Render"
echo "   2. The system will automatically fallback"
echo ""
echo "🔄 Switch to Hugging Face (if others fail):"
echo "   1. Ensure HUGGINGFACE_API_KEY is set in Render"
echo "   2. System will use HF as fallback"
echo ""

echo "🎯 Quick Test Commands:"
echo "======================"
echo ""
echo "# Test if sigie endpoint is accessible"
echo "curl -X POST https://loma-org.onrender.com/api/sigie \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"message\": \"test\"}'"
echo ""
echo "# Expected responses:"
echo "# ✅ 'Authentication required' = API working, need login"
echo "# ❌ 'AI service unavailable' = API key missing"
echo "# ❌ 'AI service temporarily unavailable' = API key invalid/service down"
echo ""

echo "📞 If All Else Fails:"
echo "===================="
echo "1. Check browser console for detailed error messages"
echo "2. Try logging out and back in"
echo "3. Clear browser cache and cookies"
echo "4. Try a different browser"
echo "5. Contact OpenAI support if API key issues persist"
