#!/bin/bash

# Fix 400 Bad Request Error in HIPAA Dev Clinical Admin Chat
# https://loma-hipaa-dev.onrender.com

echo "🔧 FIXING 400 BAD REQUEST ERROR"
echo "==============================="
echo ""
echo "URL: https://loma-hipaa-dev.onrender.com"
echo "Issue: Clinical Admin chat shows 'I encountered an error'"
echo "Console: 400 Bad Request for /api/sigie"
echo ""

echo "🔍 Root Cause Analysis:"
echo "======================="
echo ""
echo "400 Bad Request typically means:"
echo "1. Invalid request format/validation failure"
echo "2. Missing required fields in request body"
echo "3. Authentication/session issues"
echo "4. Request body parsing errors"
echo ""

echo "🛠️  IMMEDIATE FIX STEPS:"
echo "========================"
echo ""

echo "STEP 1: Check Request Format"
echo "----------------------------"
echo "The sigie endpoint expects this format:"
echo ""
echo "POST /api/sigie"
echo "Content-Type: application/json"
echo "{"
echo "  \"message\": \"hello\","
echo "  \"messages\": ["
echo "    {\"role\": \"user\", \"content\": \"hello\"}"
echo "  ],"
echo "  \"context\": {"
echo "    \"clients\": [],"
echo "    \"sessions\": [],"
echo "    \"tasks\": []"
echo "  }"
echo "}"
echo ""

echo "STEP 2: Check Authentication"
echo "--------------------------"
echo "The 400 error might be caused by:"
echo "1. Not being logged in"
echo "2. Session expired"
echo "3. Invalid session cookie"
echo ""
echo "Try:"
echo "1. Log out and log back in"
echo "2. Clear browser cookies"
echo "3. Try in incognito/private mode"
echo ""

echo "STEP 3: Check Browser Console"
echo "-----------------------------"
echo "Look for these specific errors:"
echo ""
echo "🔴 'Invalid request format'"
echo "   → Request body validation failed"
echo ""
echo "🔴 'Authentication required'"
echo "   → Need to log in first"
echo ""
echo "🔴 'No message provided'"
echo "   → Missing message field"
echo ""

echo "STEP 4: Test with Proper Authentication"
echo "======================================"
echo ""
echo "1. Make sure you're logged into the app"
echo "2. Check that you have a valid session"
echo "3. Try sending a message in Clinical Admin chat"
echo "4. If still fails, check browser console for details"
echo ""

echo "STEP 5: Common Solutions"
echo "======================="
echo ""

echo "🔧 Fix 1: Login Issue"
echo "   If not logged in:"
echo "   1. Go to login page"
echo "   2. Log in with valid credentials"
echo "   3. Try Clinical Admin chat again"
echo ""

echo "🔧 Fix 2: Session Expired"
echo "   If session expired:"
echo "   1. Log out"
echo "   2. Log back in"
echo "   3. Try again"
echo ""

echo "🔧 Fix 3: Request Format"
echo "   If request format issue:"
echo "   1. Check browser console for validation errors"
echo "   2. Ensure message field is not empty"
echo "   3. Try different message content"
echo ""

echo "🎯 Quick Test Commands:"
echo "======================"
echo ""
echo "# Test with authentication (replace with actual session cookie)"
echo "curl -X POST https://loma-hipaa-dev.onrender.com/api/sigie \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -H 'Cookie: connect.sid=YOUR_SESSION_COOKIE' \\"
echo "     -d '{\"message\": \"hello\"}'"
echo ""

echo "📞 If Still Not Working:"
echo "========================"
echo "1. Check browser console for specific error messages"
echo "2. Verify you're logged in"
echo "3. Try logging out and back in"
echo "4. Clear browser cache and cookies"
echo "5. Try in a different browser"
