#!/bin/bash

# Fix for 503 Service Unavailable Error in Production Sigie
# Based on browser console showing multiple 503 errors for api/sigie

echo "🚨 CRITICAL: 503 Service Unavailable Error Fix"
echo "=============================================="
echo ""

echo "📋 Issue Confirmed:"
echo "   Browser Console: Multiple 503 errors for api/sigie endpoint"
echo "   Status: Service Unavailable"
echo "   Impact: Clinical Admin chat completely non-functional"
echo ""

echo "🔍 Root Cause Analysis:"
echo "======================="
echo ""
echo "The 503 error occurs in these scenarios (from sigie route code):"
echo ""
echo "1. API Key Not Configured (lines 104-108):"
echo "   - OPENAI_API_KEY not set in Render environment"
echo "   - Returns: 'AI service unavailable' + 'API key not configured'"
echo ""
echo "2. AI Service API Call Failed (lines 337-341):"
echo "   - OpenAI API key invalid/expired"
echo "   - OpenAI API rate limit exceeded"
echo "   - OpenAI service outage"
echo "   - Returns: 'AI service temporarily unavailable'"
echo ""

echo "🛠️  IMMEDIATE FIX STEPS:"
echo "========================"
echo ""

echo "STEP 1: Check Render Environment Variables"
echo "----------------------------------------"
echo "1. Go to https://dashboard.render.com"
echo "2. Find your 'loma-platform' service"
echo "3. Go to Environment tab"
echo "4. Check these variables:"
echo ""
echo "   ✅ OPENAI_API_KEY"
echo "      - Should start with 'sk-'"
echo "      - Should be 51 characters long"
echo "      - Should be valid and not expired"
echo ""
echo "   ✅ ANTHROPIC_API_KEY (backup)"
echo "      - Should start with 'sk-ant-'"
echo "      - Should be 39 characters long"
echo ""
echo "   ✅ HUGGINGFACE_API_KEY (backup)"
echo "      - Should start with 'hf_'"
echo "      - Should be 37 characters long"
echo ""

echo "STEP 2: Test API Keys"
echo "-------------------"
echo "If you have access to your OpenAI API key, test it:"
echo ""
echo "curl -H 'Authorization: Bearer YOUR_OPENAI_KEY' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"model\": \"gpt-3.5-turbo\", \"messages\": [{\"role\": \"user\", \"content\": \"hello\"}]}' \\"
echo "     https://api.openai.com/v1/chat/completions"
echo ""
echo "Expected responses:"
echo "✅ 200 OK = API key is valid"
echo "❌ 401 Unauthorized = API key invalid"
echo "❌ 429 Too Many Requests = Rate limit exceeded"
echo ""

echo "STEP 3: Check Render Service Logs"
echo "--------------------------------"
echo "1. In Render dashboard, go to Logs tab"
echo "2. Look for these error patterns:"
echo ""
echo "   🔑 'OPENAI_API_KEY not set in environment variables'"
echo "      → Fix: Add/update OPENAI_API_KEY in Render"
echo ""
echo "   🔑 '[Sigie] OpenAI API Error:'"
echo "      → Fix: Check API key validity or OpenAI service status"
echo ""
echo "   🔑 'AI service temporarily unavailable'"
echo "      → Fix: API call failed, check OpenAI service"
echo ""

echo "STEP 4: Common Solutions"
echo "======================="
echo ""

echo "🔑 If API Key Missing:"
echo "   1. Go to Render dashboard > Environment"
echo "   2. Add OPENAI_API_KEY with your valid key"
echo "   3. Redeploy the service"
echo ""

echo "🔑 If API Key Invalid:"
echo "   1. Generate new API key at https://platform.openai.com/api-keys"
echo "   2. Update OPENAI_API_KEY in Render"
echo "   3. Redeploy the service"
echo ""

echo "⏱️  If Rate Limit Exceeded:"
echo "   1. Check usage at https://platform.openai.com/usage"
echo "   2. Wait 1 hour for reset"
echo "   3. Consider upgrading OpenAI plan"
echo ""

echo "🔄 If OpenAI Service Down:"
echo "   1. Check https://status.openai.com"
echo "   2. Wait for service restoration"
echo "   3. Use Anthropic as backup (if ANTHROPIC_API_KEY is set)"
echo ""

echo "STEP 5: Emergency Fallback"
echo "========================="
echo ""
echo "If OpenAI is completely down, switch to Anthropic:"
echo ""
echo "1. Ensure ANTHROPIC_API_KEY is set in Render"
echo "2. The system will automatically fallback to Anthropic"
echo "3. Redeploy if needed"
echo ""

echo "🎯 Quick Verification:"
echo "====================="
echo ""
echo "After fixing, test with:"
echo "curl -X POST https://loma-org.onrender.com/api/sigie \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"message\": \"test\"}'"
echo ""
echo "Expected responses:"
echo "✅ 'Authentication required' = Fixed! (API working, need login)"
echo "❌ 'AI service unavailable' = Still broken (API key issue)"
echo "❌ 'AI service temporarily unavailable' = Still broken (API issue)"
echo ""

echo "📞 If Still Not Working:"
echo "========================"
echo "1. Check Render service logs for detailed error messages"
echo "2. Verify API key format and validity"
echo "3. Test API key directly with OpenAI"
echo "4. Consider temporary fallback to Anthropic API"
echo "5. Contact OpenAI support if API key issues persist"
