#!/bin/bash

# Fix Intermittent 502 Errors in Incognito Mode
# https://loma-hipaa-dev.onrender.com

echo "🔧 FIXING INTERMITTENT 502 ERRORS"
echo "================================="
echo ""
echo "Issue: 502 Bad Gateway in incognito window"
echo "Status: Service responding HTTP 200 from server"
echo "Cause: Browser/CDN caching or intermittent instability"
echo ""

echo "🔍 Diagnosis:"
echo "============="
echo ""
echo "✅ Server Status: HTTP 200 OK (consistent)"
echo "❌ Browser Status: 502 Bad Gateway (incognito)"
echo ""
echo "This indicates:"
echo "1. Service is running but unstable"
echo "2. Browser/CDN caching issues"
echo "3. Intermittent service crashes"
echo "4. Load balancing problems"
echo ""

echo "🛠️  IMMEDIATE FIX STEPS:"
echo "========================"
echo ""

echo "STEP 1: Clear Browser Cache"
echo "---------------------------"
echo "1. Close all browser windows"
echo "2. Clear browser cache completely"
echo "3. Restart browser"
echo "4. Try incognito mode again"
echo ""

echo "STEP 2: Force Refresh"
echo "--------------------"
echo "1. Press Ctrl+Shift+R (or Cmd+Shift+R on Mac)"
echo "2. This forces a hard refresh bypassing cache"
echo "3. Or try Ctrl+F5"
echo ""

echo "STEP 3: Check Render Service Status"
echo "----------------------------------"
echo "1. Go to https://dashboard.render.com"
echo "2. Find your 'loma-hipaa-dev' service"
echo "3. Check if service shows as 'Live'"
echo "4. Look at the Logs tab for any crash messages"
echo ""

echo "STEP 4: Manual Redeploy"
echo "======================"
echo ""
echo "If service is unstable:"
echo "1. Go to Render dashboard"
echo "2. Find 'loma-hipaa-dev' service"
echo "3. Click 'Manual Deploy'"
echo "4. Select 'Deploy latest commit'"
echo "5. Wait for deployment to complete"
echo ""

echo "STEP 5: Check Service Logs"
echo "========================="
echo ""
echo "Look for these error patterns in Render logs:"
echo ""
echo "🔴 'Error: listen EADDRINUSE'"
echo "   → Port binding conflict"
echo ""
echo "🔴 'Error: Cannot find package'"
echo "   → Missing dependencies"
echo ""
echo "🔴 'Error: connect ECONNREFUSED'"
echo "   → Database connection failed"
echo ""
echo "🔴 'Process exited with code 1'"
echo "   → Application crash"
echo ""

echo "STEP 6: Alternative Access Methods"
echo "================================="
echo ""
echo "Try these alternatives:"
echo "1. Different browser (Chrome, Firefox, Safari)"
echo "2. Different device/network"
echo "3. VPN or different internet connection"
echo "4. Mobile browser"
echo ""

echo "🎯 Quick Test Commands:"
echo "======================"
echo ""
echo "# Test service from command line"
echo "curl -I https://loma-hipaa-dev.onrender.com"
echo ""
echo "# Test with different user agent"
echo "curl -H 'User-Agent: Mozilla/5.0' https://loma-hipaa-dev.onrender.com"
echo ""
echo "# Test health endpoint"
echo "curl https://loma-hipaa-dev.onrender.com/health"
echo ""

echo "📞 If Still Getting 502:"
echo "======================="
echo "1. Check Render service logs for crash messages"
echo "2. Verify all environment variables are set"
echo "3. Try manual redeploy"
echo "4. Check if service is hitting resource limits"
echo "5. Contact Render support if issue persists"
