#!/bin/bash

# Fix 502 Bad Gateway Error on Render HIPAA Dev Deployment
# https://loma-hipaa-dev.onrender.com

echo "🚨 FIXING 502 BAD GATEWAY ERROR"
echo "================================"
echo ""
echo "URL: https://loma-hipaa-dev.onrender.com"
echo "Error: 502 Bad Gateway"
echo "Status: Service unavailable"
echo ""

echo "🔍 Root Cause Analysis:"
echo "======================="
echo ""
echo "502 Bad Gateway typically means:"
echo "1. Application crashed during startup"
echo "2. Missing environment variables"
echo "3. Port binding issues"
echo "4. Database connection failures"
echo "5. Build/deployment errors"
echo ""

echo "🛠️  IMMEDIATE FIX STEPS:"
echo "========================"
echo ""

echo "STEP 1: Check Render Dashboard"
echo "-----------------------------"
echo "1. Go to https://dashboard.render.com"
echo "2. Find your 'loma-hipaa-dev' service"
echo "3. Go to Logs tab"
echo "4. Look for these error patterns:"
echo ""
echo "   🔴 'Error: Cannot find package'"
echo "      → Missing dependencies"
echo ""
echo "   🔴 'Error: listen EADDRINUSE'"
echo "      → Port binding issue"
echo ""
echo "   🔴 'Error: connect ECONNREFUSED'"
echo "      → Database connection failed"
echo ""
echo "   🔴 'Error: OPENAI_API_KEY not set'"
echo "      → Missing environment variables"
echo ""

echo "STEP 2: Check Environment Variables"
echo "----------------------------------"
echo "In Render dashboard > Environment tab, verify:"
echo ""
echo "✅ Required Variables:"
echo "   - DATABASE_URL (PostgreSQL connection)"
echo "   - SESSION_SECRET (random string)"
echo "   - NODE_ENV=production"
echo ""
echo "✅ AI Integration Variables:"
echo "   - OPENAI_API_KEY (optional but recommended)"
echo "   - ANTHROPIC_API_KEY (optional backup)"
echo "   - HUGGINGFACE_API_KEY (optional backup)"
echo ""

echo "STEP 3: Common Fixes"
echo "===================="
echo ""

echo "🔧 Fix 1: Missing Dependencies"
echo "   If logs show 'Cannot find package':"
echo "   1. Go to Render dashboard"
echo "   2. Trigger manual redeploy"
echo "   3. Or push new commit to trigger rebuild"
echo ""

echo "🔧 Fix 2: Port Binding Issues"
echo "   If logs show 'EADDRINUSE' or port errors:"
echo "   1. Ensure server listens on process.env.PORT"
echo "   2. Check server/index.ts port configuration"
echo ""

echo "🔧 Fix 3: Database Connection"
echo "   If logs show 'ECONNREFUSED' or database errors:"
echo "   1. Verify DATABASE_URL is correct"
echo "   2. Check database service is running"
echo "   3. Ensure database allows connections"
echo ""

echo "🔧 Fix 4: Environment Variables"
echo "   If logs show 'not set' errors:"
echo "   1. Add missing environment variables"
echo "   2. Redeploy service"
echo ""

echo "STEP 4: Manual Redeploy"
echo "======================"
echo ""
echo "If all else fails:"
echo "1. Go to Render dashboard"
echo "2. Find your 'loma-hipaa-dev' service"
echo "3. Click 'Manual Deploy'"
echo "4. Select 'Deploy latest commit'"
echo "5. Wait for deployment to complete"
echo ""

echo "STEP 5: Verify Fix"
echo "=================="
echo ""
echo "After fixing, test:"
echo "curl -I https://loma-hipaa-dev.onrender.com"
echo ""
echo "Expected responses:"
echo "✅ HTTP/2 200 = Fixed!"
echo "❌ HTTP/2 502 = Still broken"
echo "❌ HTTP/2 503 = Service unavailable"
echo ""

echo "🎯 Quick Diagnostic Commands:"
echo "============================"
echo ""
echo "# Check service status"
echo "curl -I https://loma-hipaa-dev.onrender.com"
echo ""
echo "# Check if health endpoint works"
echo "curl https://loma-hipaa-dev.onrender.com/health"
echo ""
echo "# Check if API endpoint works"
echo "curl https://loma-hipaa-dev.onrender.com/api/sigie"
echo ""

echo "📞 If Still Not Working:"
echo "========================"
echo "1. Check Render service logs for specific error messages"
echo "2. Verify all environment variables are set"
echo "3. Ensure database service is running"
echo "4. Try manual redeploy"
echo "5. Contact Render support if issue persists"
